=== Xsals002/xsals002---Pa-an/sami_salama.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">

  <xs:element name="konfigurace_Paran">
    
  </xs:element>

  <xs:complexType name="profil">
  <xs:sequence>
    <xs:element name="ucet">
           <xs:complexType>
            <xs:sequence>
              <xs:element name="nazev_uctu" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="stav" type="akt_neakt"/>
              <xs:element name="beta_verze" type="zap_vyp"/>
            </xs:sequence>
          </xs:complexType>
   </xs:element>
   <xs:element name="rozhrani">
      <xs:complexType>
            <xs:sequence>
              <xs:element name="jazyk" type="xs:string" default="Cestina"/>
              <xs:element name="domovska_obrazovka" type="xs:string" default="Obchod"/>
              <xs:element name="vhled" type="xs:string" default="Dark"/>
              <xs:element name="po_spusteni_windows" type="ano_ne"/>
              <xs:element name="maximalizovat" type="ano_ne"/>
              <xs:element name="zalozky">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="zObchod" type="zap_vyp"/>
                      <xs:attribute name="zHry" type="zap_vyp"/>
                      <xs:attribute name="zKomunita" type="zap_vyp"/>
                      <xs:attribute name="zNastaveni" type="zap_vyp"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="komunita">
     <xs:complexType>
            <xs:sequence>
              <xs:element name="prezdivka" type="xs:string"/>
              <xs:element name="auto_prihlaseni" type="ano_ne"/>
              <xs:element name="cas_v_chatu" type="ano_ne"/>
              <xs:element name="upozorneni_zvuky">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="pritel_ve_hre">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="upozorneni" type="ano_ne"/>
                            <xs:attribute name="zvuk" type="ano_ne"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="pritel_online">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="upozorneni" type="ano_ne"/>
                            <xs:attribute name="zvuk" type="ano_ne"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="oznameni_skupiny">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="upozorneni" type="ano_ne"/>
                            <xs:attribute name="zvuk" type="ano_ne"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="nova_zprava">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="upozorneni" type="ano_ne"/>
                            <xs:attribute name="zvuk" type="ano_ne"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
   </xs:element>
   <xs:element name="aplikace_ve_hre">
     <xs:complexType>
            <xs:sequence>
              <xs:element name="klavesova_zkratka" type="xs:string"/>
              <xs:element name="screenshot" type="xs:string"/>
              <xs:element name="screenshot_konf">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="umisteni_screenshotu" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="ukazatel_fps">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="zobrazit_fps" type="ano_ne"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
   </xs:element>
   <xs:element name="hlas">
     <xs:complexType>
            <xs:sequence>
              <xs:element name="nazev_mikrofonu" type="xs:string"/>
              <xs:element name="hlasitost_mikrofonu" type="procenta"/>
              <xs:element name="hlasitost_prijmu" type="procenta"/>
              <xs:element name="zesilit_mikrofon" type="ano_ne"/>
              <xs:element name="hlasova_konverzace">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="automaticky" type="ano_ne"/>
                      <xs:attribute name="po_stisknuti_tlacitka" type="ano_ne"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
   </xs:element>
   <xs:element name="hudebni_prehravac">
     <xs:complexType>
            <xs:sequence>
              <xs:element name="umisteni">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="umisteni_hudby" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="automaticky_prohledat" type="ano_ne"/>
              <xs:element name="hlasitost_hudby" type="procenta"/>
              <xs:element name="pozastavit_hudbu">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="pri_spusteni_aplikace" type="ano_ne"/>
                      <xs:attribute name="pri_hlasove_konverzaci" type="ano_ne"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="upozorneni_o_nove_skladbe" type="ano_ne"/>
            </xs:sequence>
          </xs:complexType>
   </xs:element>
   <xs:element name="stream">
     <xs:complexType>
            <xs:sequence>
              <xs:element name="stav_prenosu" type="akt_neakt"/>
              <xs:element name="soukromi" type="soukromi"/>
              <xs:element name="rozliseni_videa" type="rozliseni"/>
              <xs:element name="maximalni_rychlost_prenosu" type="xs:string"/>
              <xs:element name="optimalizace" type="optimalizace"/>
              <xs:element name="konverzace_divaku">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="zobrazit_konverzaci_divaku" type="ano_ne"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="nahravat_zvuk_z_mikrofonu" type="ano_ne"/>
              <xs:element name="zobrazit_statistiky" type="ano_ne"/>
            </xs:sequence>
          </xs:complexType>
   </xs:element>
   <xs:element name="stahovani">
     <xs:complexType>
            <xs:sequence>
              <xs:element name="cil">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="umisteni_her" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="oblast_stahovani" type="xs:string"/>
              <xs:element name="stahovani_behem_hrani" type="ano_ne"/>
              <xs:element name="stahovani_behem_streamu" type="ano_ne"/>
              <xs:element name="zobrazit_rychlost" type="ano_ne"/>
            </xs:sequence>
          </xs:complexType>
   </xs:element>
  </xs:sequence>
  </xs:complexType> 

  <xs:simpleType name="zap_vyp">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Zapnuto"/>
      <xs:enumeration value="Vypnuto"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="akt_neakt">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Aktivni"/>
      <xs:enumeration value="Neaktivni"/>
    </xs:restriction>
  </xs:simpleType>  

  <xs:simpleType name="ano_ne">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ano"/>
      <xs:enumeration value="Ne"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="procenta">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="soukromi">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Verejne"/>
      <xs:enumeration value="Pouze pratele"/>
      <xs:enumeration value="Jen ja"/>
    </xs:restriction>
  </xs:simpleType> 

  <xs:simpleType name="rozliseni">
    <xs:restriction base="xs:string">
      <xs:enumeration value="640x360"/>
      <xs:enumeration value="854x480"/>
      <xs:enumeration value="1280x720"/>
      <xs:enumeration value="1920x1080"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="optimalizace">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Pro nejlepsi vykon"/>
      <xs:enumeration value="Pro nejlepsi kvalitu"/>
    </xs:restriction>
  </xs:simpleType> 

  <xs:element name="stav">
    <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Aktivni"/>
      <xs:enumeration value="Neaktivni"/>
    </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="jazyk">
    <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Cestina"/>
      <xs:enumeration value="Slovenstina"/>
      <xs:enumeration value="Anglictina"/>
      <xs:enumeration value="Rustina"/>
    </xs:restriction>
    </xs:simpleType>
  </xs:element>
    <xs:element name="domovska_obrazovka">
    <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Obchod"/>
      <xs:enumeration value="Komunita"/>
      <xs:enumeration value="Hry"/>
    </xs:restriction>
    </xs:simpleType>
  </xs:element>
      <xs:element name="vzhled">
    <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dark"/>
      <xs:enumeration value="Light"/>
    </xs:restriction>
    </xs:simpleType>
  </xs:element>
    <xs:element name="oblast_stahovani">
    <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ceska republika"/>
      <xs:enumeration value="Slovensko"/>
      <xs:enumeration value="Nemecko"/>
      <xs:enumeration value="Britanie"/>
      <xs:enumeration value="Rusko"/>
      <xs:enumeration value="USA"/>
    </xs:restriction>
    </xs:simpleType>
  </xs:element>


</xs:schema>

=== Xsals002/xsals002---Pa-an/sami_salama.xml
<?xml version="1.0" encoding="UTF-8"?>

<konfigurace_Paran xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sami_salama.xsd">
    	<!-- 1. uzivatel -->
    <ucet>
                <nazev_uctu>xsals002</nazev_uctu>
                <email>xsals@gmail.com</email>
		<stav>Aktivni</stav>
		<beta_verze>Vypnuto</beta_verze>
	<rozhrani>
		<jazyk>Cestina</jazyk>
		<domovska_obrazovka>Obchod</domovska_obrazovka>
		<vhled>Dark</vhled>
		<po_spusteni_windows>Ano</po_spusteni_windows>
		<maximalizovat>Ano</maximalizovat>
		<zalozky zObchod="Zapnuto" zHry="Zapnuto" zKomunita="Zapnuto" zNastaveni="Zapnuto"/>
	</rozhrani>
	<komunita>
		<prezdivka>CzuRules</prezdivka>
		<auto_prihlaseni>Ano</auto_prihlaseni>
		<cas_v_chatu>Ne</cas_v_chatu>
		<upozorneni_zvuky>
			<pritel_ve_hre upozorneni="Ano" zvuk="Ne"/>
			<pritel_online upozorneni="Ne" zvuk="Ne"/>
			<oznameni_skupiny upozorneni="Ano" zvuk="Ne"/>
			<nova_zprava upozorneni="Ano" zvuk="Ano"/>
		</upozorneni_zvuky>
	</komunita>
	<aplikace_ve_hre>
		<klavesova_zkratka>Shift+Tab</klavesova_zkratka>
		<screenshot>F12</screenshot>
		<screenshot_konf umisteni_screenshotu="D:\\Hry\\Screenshoty"/>
		<ukazatel_fps zobrazit_fps="Ano">Vpravo nahore</ukazatel_fps>
	</aplikace_ve_hre>
	<hlas>
		<nazev_mikrofonu>CreativeFatality</nazev_mikrofonu>
		<hlasitost_mikrofonu>100</hlasitost_mikrofonu>
		<hlasitost_prijmu>90</hlasitost_prijmu>
		<zesilit_mikrofon>Ne</zesilit_mikrofon>
		<hlasova_konverzace automaticky="Ano" po_stisknuti_tlacitka="Ne"/>
	</hlas>
	<hudebni_prehravac>
		<umisteni umisteni_hudby="D:\\Music"/>
		<automaticky_prohledat>Ne</automaticky_prohledat>
		<hlasitost_hudby>100</hlasitost_hudby>
		<pozastavit_hudbu pri_spusteni_aplikace="Ne" pri_hlasove_konverzaci="Ano"/>
		<upozorneni_o_nove_skladbe>Ano</upozorneni_o_nove_skladbe>
	</hudebni_prehravac>
	<stream>
		<stav_prenosu>Neaktivni</stav_prenosu>
		<soukromi>Pouze pratele</soukromi>
		<rozliseni_videa>1280x720</rozliseni_videa>
		<maximalni_rychlost_prenosu>2500 kbit/s</maximalni_rychlost_prenosu>
		<optimalizace>Pro nejlepsi kvalitu</optimalizace>
		<konverzace_divaku zobrazit_konverzaci_divaku="Ano">Vlevo nahore</konverzace_divaku>
		<nahravat_zvuk_z_mikrofonu>Ne</nahravat_zvuk_z_mikrofonu>
		<zobrazit_statistiky>Ne</zobrazit_statistiky>
	</stream>
	<stahovani>
		<cil umisteni_her="D:\\Hry"/>
		<oblast_stahovani>Ceska republika</oblast_stahovani>
		<stahovani_behem_hrani>Ano</stahovani_behem_hrani>
		<stahovani_behem_streamu>Ne</stahovani_behem_streamu>
		<zobrazit_rychlost>Ano</zobrazit_rychlost>
	</stahovani>
    </ucet>
	<!-- 2. uzivatel -->
    <ucet>
        <nazev_uctu>perinka</nazev_uctu>
		<email>t.horak@gmail.com</email>
		<stav>Aktivni</stav>
		<beta_verze>Vypnuto</beta_verze>
	<rozhrani>
		<jazyk>Cestina</jazyk>
		<domovska_obrazovka>Hry</domovska_obrazovka>
		<vhled>Dark</vhled>
		<po_spusteni_windows>Ano</po_spusteni_windows>
		<maximalizovat>Ne</maximalizovat>
		<zalozky zObchod="Vypnuto" zHry="Zapnuto" zKomunita="Zapnuto" zNastaveni="Vypnuto"/>
	</rozhrani>
	<komunita>
		<prezdivka>Perinka</prezdivka>
		<auto_prihlaseni>Ano</auto_prihlaseni>
		<cas_v_chatu>Ano</cas_v_chatu>
		<upozorneni_zvuky>
			<pritel_ve_hre upozorneni="Ano" zvuk="Ano"/>
			<pritel_online upozorneni="Ne" zvuk="Ne"/>
			<oznameni_skupiny upozorneni="Ne" zvuk="Ne"/>
			<nova_zprava upozorneni="Ano" zvuk="Ano"/>
		</upozorneni_zvuky>
	</komunita>
	<aplikace_ve_hre>
		<klavesova_zkratka>Ctrl+Shift+Tab</klavesova_zkratka>
		<screenshot>F11</screenshot>
		<screenshot_konf umisteni_screenshotu="D:\\Gamesy\\Obrazky_z_her"/>
		<ukazatel_fps zobrazit_fps="Ne">Vypnuto</ukazatel_fps>
	</aplikace_ve_hre>
	<hlas>
		<nazev_mikrofonu>HP</nazev_mikrofonu>
		<hlasitost_mikrofonu>98</hlasitost_mikrofonu>
		<hlasitost_prijmu>68</hlasitost_prijmu>
		<zesilit_mikrofon>Ano</zesilit_mikrofon>
		<hlasova_konverzace automaticky="Ne" po_stisknuti_tlacitka="Ano"/>
	</hlas>
	<hudebni_prehravac>
		<umisteni umisteni_hudby="D:\\Hudba"/>
		<automaticky_prohledat>Ne</automaticky_prohledat>
		<hlasitost_hudby>50</hlasitost_hudby>
		<pozastavit_hudbu pri_spusteni_aplikace="Ne" pri_hlasove_konverzaci="Ano"/>
		<upozorneni_o_nove_skladbe>Ne</upozorneni_o_nove_skladbe>
	</hudebni_prehravac>
	<stream>
		<stav_prenosu>Neaktivni</stav_prenosu>
		<soukromi>Verejne</soukromi>
		<rozliseni_videa>854x480</rozliseni_videa>
		<maximalni_rychlost_prenosu>3500 kbit/s</maximalni_rychlost_prenosu>
		<optimalizace>Pro nejlepsi vykon</optimalizace>
		<konverzace_divaku zobrazit_konverzaci_divaku="Ne">Vypnuto</konverzace_divaku>
		<nahravat_zvuk_z_mikrofonu>Ano</nahravat_zvuk_z_mikrofonu>
		<zobrazit_statistiky>Ano</zobrazit_statistiky>
	</stream>
	<stahovani>
		<cil umisteni_her="D:\\Gamesy"/>
		<oblast_stahovani>Ceska republika</oblast_stahovani>
		<stahovani_behem_hrani>Ne</stahovani_behem_hrani>
		<stahovani_behem_streamu>Ne</stahovani_behem_streamu>
		<zobrazit_rychlost>Ano</zobrazit_rychlost>
	</stahovani>
    </ucet>

	<!-- 3. uzivatel -->
    <ucet>
                <nazev_uctu>pavlov900</nazev_uctu>
		<email>andrej.pavlov@gmail.com</email>
		<stav>Aktivni</stav>
		<beta_verze>Zapnuto</beta_verze>

	<rozhrani>
		<jazyk>Rustina</jazyk>
		<domovska_obrazovka>Obchod</domovska_obrazovka>
		<vhled>Light</vhled>
		<po_spusteni_windows>Ne</po_spusteni_windows>
		<maximalizovat>Ano</maximalizovat>
		<zalozky zObchod="Zapnuto" zHry="Zapnuto" zKomunita="Vypnuto" zNastaveni="Zapnuto"/>
	</rozhrani>
	<komunita>
		<prezdivka>MaroznoeRU</prezdivka>
		<auto_prihlaseni>Ne</auto_prihlaseni>
		<cas_v_chatu>Ano</cas_v_chatu>
		<upozorneni_zvuky>
			<pritel_ve_hre upozorneni="Ne" zvuk="Ne"/>
			<pritel_online upozorneni="Ne" zvuk="Ne"/>
			<oznameni_skupiny upozorneni="Ne" zvuk="Ne"/>
			<nova_zprava upozorneni="Ano" zvuk="Ne"/>
		</upozorneni_zvuky>
	</komunita>
	<aplikace_ve_hre>
		<klavesova_zkratka>Shift+F2</klavesova_zkratka>
		<screenshot>F5</screenshot>
		<screenshot_konf umisteni_screenshotu="C:\\Users\\Pavel\\Igry"/>
		<ukazatel_fps zobrazit_fps="Ano">Vpravo nahore</ukazatel_fps>
	</aplikace_ve_hre>
	<hlas>
		<nazev_mikrofonu>Razer</nazev_mikrofonu>
		<hlasitost_mikrofonu>100</hlasitost_mikrofonu>
		<hlasitost_prijmu>100</hlasitost_prijmu>
		<zesilit_mikrofon>Ano</zesilit_mikrofon>
		<hlasova_konverzace automaticky="Ne" po_stisknuti_tlacitka="Ano"/>
	</hlas>
	<hudebni_prehravac>
		<umisteni umisteni_hudby="C:\\Users\\Pavel\\Muzika"/>
		<automaticky_prohledat>Ano</automaticky_prohledat>
		<hlasitost_hudby>100</hlasitost_hudby>
		<pozastavit_hudbu pri_spusteni_aplikace="Ano" pri_hlasove_konverzaci="Ano"/>
		<upozorneni_o_nove_skladbe>Ne</upozorneni_o_nove_skladbe>
	</hudebni_prehravac>
	<stream>
		<stav_prenosu>Aktivni</stav_prenosu>
		<soukromi>Pouze pratele</soukromi>
		<rozliseni_videa>1920x1080</rozliseni_videa>
		<maximalni_rychlost_prenosu>3000 kbit/s</maximalni_rychlost_prenosu>
		<optimalizace>Pro nejlepsi kvalitu</optimalizace>
		<konverzace_divaku zobrazit_konverzaci_divaku="Ano">Vpravo nahore</konverzace_divaku>
		<nahravat_zvuk_z_mikrofonu>Ano</nahravat_zvuk_z_mikrofonu>
		<zobrazit_statistiky>Ano</zobrazit_statistiky>
	</stream>
	<stahovani>
		<cil umisteni_her="C:\\Users\\Pavel\\Igry"/>
		<oblast_stahovani>Rusko</oblast_stahovani>
		<stahovani_behem_hrani>Ne</stahovani_behem_hrani>
		<stahovani_behem_streamu>Ne</stahovani_behem_streamu>
		<zobrazit_rychlost>Ne</zobrazit_rychlost>
	</stahovani>
    </ucet>

	<!-- 4. uzivatel -->
    <ucet>
        <nazev_uctu>cichlu</nazev_uctu>
		<email>l.cichy@seznam.cz</email>
		<stav>Neaktivni</stav>
		<beta_verze>Vypnuto</beta_verze>
	<rozhrani>
		<jazyk>Cestina</jazyk>
		<domovska_obrazovka>Obchod</domovska_obrazovka>
		<vhled>Dark</vhled>
		<po_spusteni_windows>Ne</po_spusteni_windows>
		<maximalizovat>Ano</maximalizovat>
		<zalozky zObchod="Vypnuto" zHry="Zapnuto" zKomunita="Vypnuto" zNastaveni="Vypnuto"/>
	</rozhrani>
	<komunita>
		<prezdivka>CicheKridlo</prezdivka>
		<auto_prihlaseni>Ne</auto_prihlaseni>
		<cas_v_chatu>Ne</cas_v_chatu>
		<upozorneni_zvuky>
			<pritel_ve_hre upozorneni="Ne" zvuk="Ne"/>
			<pritel_online upozorneni="Ne" zvuk="Ne"/>
			<oznameni_skupiny upozorneni="Ne" zvuk="Ne"/>
			<nova_zprava upozorneni="Ano" zvuk="Ano"/>
		</upozorneni_zvuky>
	</komunita>
	<aplikace_ve_hre>
		<klavesova_zkratka>Shift+Tab</klavesova_zkratka>
		<screenshot>Home</screenshot>
		<screenshot_konf umisteni_screenshotu="D:\\Obrazky"/>
		<ukazatel_fps zobrazit_fps="Ne">Vypnuto</ukazatel_fps>
	</aplikace_ve_hre>
	<hlas>
		<nazev_mikrofonu>Nenalezeno</nazev_mikrofonu>
		<hlasitost_mikrofonu>0</hlasitost_mikrofonu>
		<hlasitost_prijmu>0</hlasitost_prijmu>
		<zesilit_mikrofon>Ne</zesilit_mikrofon>
		<hlasova_konverzace automaticky="Ano" po_stisknuti_tlacitka="Ne"/>
	</hlas>
	<hudebni_prehravac>
		<umisteni umisteni_hudby="D:\\Hudba"/>
		<automaticky_prohledat>Ne</automaticky_prohledat>
		<hlasitost_hudby>0</hlasitost_hudby>
		<pozastavit_hudbu pri_spusteni_aplikace="Ano" pri_hlasove_konverzaci="Ano"/>
		<upozorneni_o_nove_skladbe>Ne</upozorneni_o_nove_skladbe>
	</hudebni_prehravac>
	<stream>
		<stav_prenosu>Neaktivni</stav_prenosu>
		<soukromi>Pouze pratele</soukromi>
		<rozliseni_videa>1280x720</rozliseni_videa>
		<maximalni_rychlost_prenosu>2000 kbit/s</maximalni_rychlost_prenosu>
		<optimalizace>Pro nejlepsi vykon</optimalizace>
		<konverzace_divaku zobrazit_konverzaci_divaku="Ne">Vypnuto</konverzace_divaku>
		<nahravat_zvuk_z_mikrofonu>Ne</nahravat_zvuk_z_mikrofonu>
		<zobrazit_statistiky>Ne</zobrazit_statistiky>
	</stream>
	<stahovani>
		<cil umisteni_her="D:\\Software\\Hry"/>
		<oblast_stahovani>Ceska republika</oblast_stahovani>
		<stahovani_behem_hrani>Ne</stahovani_behem_hrani>
		<stahovani_behem_streamu>Ne</stahovani_behem_streamu>
